sudo: required

language: go

go:
  - 1.11.x

dist: xenial

# Only clone the most recent commit.
git:
  depth: 1

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
  - make install-dep
  - make dep

script:
  # Here sudo -E env "PATH=$PATH" make test is required for running tests with
  # sudo permissions since it is testing iptables, sudo or root permissions are required.
  -  sudo -E env "PATH=$PATH" make test
