sudo: required

language: go

go:
  - 1.11.x

dist: xenial

# Only clone the most recent commit.
git:
  depth: 1

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
  - make install-dep
  - make dep

script:
  - sudo make test
