config:
    rules:
    -   interface:
        - docker0
        - docker_gwbridge
    -   allow:
        - 192.168.1.15
        - 192.168.2.15
        - 192.168.3.15
        - 192.168.4.15
        port: 3000
    -   port: 5601
    -   allow:
        - 10.0.1.15
        - 10.1.0.25
        protocol: tcp
        port: 9100
